#!/bin/bash

# 更新至 vendor/bin

# 功能 
# 1. initial 根据模型名字 - 初始化文件夹和文件 区分 backend 和 frontend
# 2. autocreate 过滤文件, 自动生成代码

# 入参 -h
# 入参 -v

# help 函数
# 根据输入文件夹遍历, 文件夹格式可以通过配置文件制定
# 根据输入文件名生成代码 和 ut文件代码
# 判断文件名是否存在

# 工厂函数
# 根据url和文件名, 判断调用生成器